// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlQnFbVQhxed-Cd4bNggAQSw4HhyZbA3k',
    appId: '1:117790585867:web:0f54e9892101f726ec830e',
    messagingSenderId: '117790585867',
    projectId: 'qrcode-720b6',
    authDomain: 'qrcode-720b6.firebaseapp.com',
    storageBucket: 'qrcode-720b6.appspot.com',
    measurementId: 'G-FV4JWEQH5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvb3hLUSCTdiBtOmg5i-kDpwBRMIRDsfA',
    appId: '1:117790585867:android:696415e34b76b8e2ec830e',
    messagingSenderId: '117790585867',
    projectId: 'qrcode-720b6',
    storageBucket: 'qrcode-720b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT5uJ1NLt8zYYTA2FMBsV2Ww8m9LHwbig',
    appId: '1:117790585867:ios:536071b4bb3936c4ec830e',
    messagingSenderId: '117790585867',
    projectId: 'qrcode-720b6',
    storageBucket: 'qrcode-720b6.appspot.com',
    iosBundleId: 'com.example.qrCodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT5uJ1NLt8zYYTA2FMBsV2Ww8m9LHwbig',
    appId: '1:117790585867:ios:cf0ee850cc8c3ab5ec830e',
    messagingSenderId: '117790585867',
    projectId: 'qrcode-720b6',
    storageBucket: 'qrcode-720b6.appspot.com',
    iosBundleId: 'com.example.qrCodeApp.RunnerTests',
  );
}
